pub const ARCH: &[&str] = &[
    "                   -`                   ",
    "                  .o+`                  ",
    "                 `ooo/                  ",
    "                `+oooo:                 ",
    "               `+oooooo:                ",
    "               -+oooooo+:               ",
    "             `/:-:++oooo+:              ",
    "            `/++++/+++++++:             ",
    "           `/++++++++++++++:            ",
    "          `/+++ooooooooooooo/`          ",
    "         ./ooosssso++osssssso+`         ",
    "        .oossssso-````/ossssss+`        ",
    "       -osssssso.      :ssssssso.       ",
    "      :osssssss/        osssso+++.      ",
    "     /ossssssss/        +ssssooo/-      ",
    "   `/ossssso+/:-        -:/+osssso+-    ",
    "  `+sso+:-`                 `.-/+oso:   ",
    " `++:.                           `-/+/  ",
    " .`                                 `/  ",
];

pub const ARCH_SMALL: &[&str] = &[
    "      /\\        ",
    "     /  \\      ",
    "    /\\   \\      ",
    "   /      \\     ",
    "  /   __   \\    ",
    " / __|  |__-\\   ",
    "/_-''    ''-_\\  ",
];

pub const NYARCH: &[&str] = &[
    "                     +*",
    "                    =**+",
    "                   -****+",
    "                  :#*****=",
    "          :=-:.  .#*******-        .",
    "           +=++++--+*******=:=++==+:",
    "           -+=+***+=+********#*==+:",
    "           :**#**##*******##***++=",
    "             =#+++***####**+++*:.",
    "            :***+-+#*=+=*#+-=**-",
    "           -*##+*#%%*::-#%%#*+##=",
    "          -#*##%%%%=    .#%%%##**+:::::::.",
    "      .::+#**#%%%%=  ..:.=%%%%#**#*:   ..-=-",
    "   .--:.+###*###**-:-::.. *%%%%*+==+..::::.",
    "  :=:  =*++++***##:      .+****++++*=..",
    "   ::-+*******+=-:   :---:..-=***###*+.",
    "    .*#*+=:.       :-:.         .:-+***:",
    "   :+=:           :-                 :-+-",
    "   :                                    .",
];

pub const NYARCH_SMALL: &[&str] = &[
    "      /\\        ",
    "     /  \\      ",
    "    /\\   \\      ",
    "   / > ω <\\     ",
    "  /   __   \\    ",
    " / __|  |__-\\   ",
    "/_-''    ''-_\\  ",
];

pub const FEDORA: &[&str] = &[
    "           .',;::::;,'.                ",
    "       .';:cccccccccccc:;,.            ",
    "    .;cccccccccccccccccccccc;.         ",
    "  .:cccccccccccccccccccccccccc:.       ",
    ".;ccccccccccccc;.:dddl:.;ccccccc;.     ",
    ".:ccccccccccccc;OWMKOOXMWd;ccccccc:.   ",
    ".:ccccccccccccc;KMMc;cc;xMMc;ccccccc:. ",
    ",cccccccccccccc;MMM.;cc;;WW:;cccccccc, ",
    ":cccccccccccccc;MMM.;cccccccccccccccc: ",
    ":ccccccc;oxOOOo;MMM000k.;cccccccccccc: ",
    "cccccc;0MMKxdd:;MMMkddc.;cccccccccccc; ",
    "ccccc;XMO';cccc;MMM.;cccccccccccccccc' ",
    "ccccc;MMo;ccccc;MMW.;ccccccccccccccc;  ",
    "ccccc;0MNc.ccc.xMMd;ccccccccccccccc;   ",
    "cccccc;dNMWXXXWM0:;cccccccccccccc:,    ",
    "cccccccc;.:odl:.;cccccccccccccc:,.     ",
    "ccccccccccccccccccccccccccccc:'.       ",
    ":ccccccccccccccccccccccc:;,..          ",
    " ':cccccccccccccccc::;,.               ",
];

pub const FEDORA_SMALL: &[&str] = &[
    "        ,'''''.    ",
    "       |   ,.  |   ",
    "       |  |  '_'   ",
    "  ,....|  |..      ",
    ".'  ,_;|   ..'     ",
    "|  |   |  |        ",
    "|  ',_,'  |        ",
    " '.     ,'         ",
    "   '''''           ",
];

pub const UBUNTU: &[&str] = &[
    "            .-/+oossssoo+/-.               ",
    "        `:+ssssssssssssssssss+:`           ",
    "      -+ssssssssssssssssssyyssss+-         ",
    "    .ossssssssssssssssssdMMMNysssso.       ",
    "   /ssssssssssshdmmNNmmyNMMMMhssssss/      ",
    "  +ssssssssshmydMMMMMMMNddddyssssssss+     ",
    " /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    ",
    ".ssssssssdMMMNhsssssssssshNMMMdssssssss.   ",
    "+sssshhhyNMMNyssssssssssssyNMMMysssssss+   ",
    "ossyNMMMNyMMhsssssssssssssshmmmhssssssso   ",
    "ossyNMMMNyMMhsssssssssssssshmmmhssssssso   ",
    "+sssshhhyNMMNyssssssssssssyNMMMysssssss+   ",
    ".ssssssssdMMMNhsssssssssshNMMMdssssssss.   ",
    " /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    ",
    "  +sssssssssdmydMMMMMMMMddddyssssssss+     ",
    "   /ssssssssssshdmNNNNmyNMMMMhssssss/      ",
    "    .ossssssssssssssssssdMMMNysssso.       ",
    "      -+sssssssssssssssssyyyssss+-         ",
    "        `:+ssssssssssssssssss+:`           ",
    "            .-/+oossssoo+/-.               ",
];

pub const UBUNTU_SMALL: &[&str] = &[
    "       ..;,; .,;,.     ",
    "    .,lool: .ooooo,    ",
    "   ;oo;:    .coool.    ",
    " ....         ''' ,l;  ",
    ":oooo,            'oo. ",
    "looooc            :oo' ",
    " '::'             ,oo: ",
    "   ,.,       .... co,  ",
    "    lo:;.   :oooo; .   ",
    "     ':ooo; cooooc     ",
    "        '''  ''''      ",
];

pub const DEBIAN: &[&str] = &[
    "          _,met$$$$$gg.          ",
    "       ,g$$$$$$$$$$$$$$$P.       ",
    "     ,g$$P\"\"       \"\"\"Y$$.\". ",
    "    ,$$P'              `$$$.     ",
    "  ',$$P       ,ggs.     `$$b:    ",
    "  `d$$'     ,$P\"'   .    $$$    ",
    "   $$P      d$'     ,    $$P     ",
    "   $$:      $$.   -    ,d$$'     ",
    "   $$;      Y$b._   _,d$P'       ",
    "   Y$$.    `.`\"Y$$$$P\"'         ",
    "   `$$b      \"-.__              ",
    "    `Y$$b                        ",
    "     `Y$$.                       ",
    "       `$$b.                     ",
    "         `Y$$b.                  ",
    "           `\"Y$b._              ",
    "               `\"\"\"\"         ",
];

pub const DEBIAN_SMALL: &[&str] = &[
    "  _____   ",
    " /  __ \\ ",
    "|  /    | ",
    "|  \\___- ",
    "-_        ",
    "  --_     ",
];

pub const DEFAULT: &[&str] = &[
    "       a8888b.           ",
    "      d888888b.          ",
    "      8P\"YP\"Y88        ",
    "      8|o||o|88          ",
    "      8'    .88          ",
    "      8`._.' Y8.         ",
    "     d/      `8b.        ",
    "    dP        Y8b.       ",
    "   d8:        ::88b.     ",
    "  d8\"          'Y88b    ",
    " :8P            :888     ",
    "  8a.          _a88P     ",
    " ._/\"Yaa      .| 88P|   ",
    " \\    YP\"    `|     `. ",
    " /     \\.___.d|    .'   ",
    " `--..__)     `._.'      ",
    "                         ",
    "                         ",
    "                         ",
];

pub const DEFAULT_SMALL: &[&str] = &[
    "   .--.       ",
    "  |o_o |      ",
    "  |:_/ |      ",
    " //   \\ \\   ",
    "(|     | )    ",
    "/'\\_   _/`\\ ",
    "\\___)=(___)/ ",
];

pub const NONE: &[&str] = &[];
